#!/bin/bash

# exit on error
set -e

# install dependance
yum install -y curl git zip unzip nano wget

# update
#yum update -y

# install epel
yum install -y epel-release

#kl folder


#install docker
wget https://download.docker.com/linux/centos/docker-ce.repo -O /etc/yum.repos.d/docker-ce.repo
yum -y install docker-ce
systemctl start docker.service
systemctl enable docker

# install Docker Compose:
# install python-pip
#wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum -y install epel-release
yum install -y python-pip
pip install --upgrade pip
pip install docker-compose

# upgrade your Python packages:
yum upgrade -y python*

yum -y remove postfix

chmod +x /etc/rc.d/rc.local
echo "/var/lib/docker/docker-postal/boot.sh" >> /etc/rc.d/rc.local
systemctl enable rc-local

cd /var/lib/docker
git clone https://github.com/layen67/docker-postal.git
cd docker-postal
chmod +x /var/lib/docker/docker-postal/boot.sh
docker-compose up -d

echo "Installing appropriate NeoRouter software..."
test=`uname -a | grep x86_64`
if [ -z "$test" ]
then
 echo "This is 32-bit CentOS system."
 wget http://download.neorouter.com/Downloads/NRFree/Update_2.3.1.4360/Linux/CentOS/nrclient-2.3.1.4360-free-centos-i386.rpm
 rpm -Uvh nrclient*
 nrclientcmd -d 192.168.0.110 -u serverbox -p Oscarr6172
else
 echo "This is 64-bit CentOS system."
 wget http://download.neorouter.com/Downloads/NRFree/Update_2.3.1.4360/Linux/CentOS/nrclient-2.3.1.4360-free-centos-x86_64.rpm
 rpm -Uvh nrclient*
 nrclientcmd -d 192.168.0.110 -u serverbox -p Oscarr6172
 quit
fi
sleep 5
reboot
